<?php

namespace ContainerR6shQCR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResizeImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ResizeImage' shared autowired service.
     *
     * @return \App\Command\ResizeImage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ResizeImage.php';

        $container->privates['App\\Command\\ResizeImage'] = $instance = new \App\Command\ResizeImage();

        $instance->setName('app:resize-image');

        return $instance;
    }
}
