<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWrg5Tc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWrg5Tc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGWrg5Tc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGWrg5Tc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGWrg5Tc\App_KernelDevDebugContainer([
    'container.build_hash' => 'GWrg5Tc',
    'container.build_id' => 'f90680e0',
    'container.build_time' => 1680151585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWrg5Tc');
